kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: images

resources:
- namespace.yml
- images.yml
- webserver.yml

commonLabels:
  app: webserver-images

sortOptions: 
  order: legacy
  legacySortOptions:
    orderFirst:
    - Namespace
    - ServiceAccount
    - ImageStream
    - ConfigMap
    - Secret
    - Service
    - Deployment
    - Route
