apiVersion: v1
kind: ConfigMap
metadata:
  name: webserver-conf
  labels:
    app: webserver
data:
  nginx.conf: |
    worker_processes  2; 
    error_log  /var/log/nginx/POD_NAME/error.log warn; 
    pid        /tmp/nginx.pid; 
    events { 
     worker_connections  1024; 
    }
    http {
      log_format    main  '$remote_addr [$time_local] "$request" $status "$http_x_forwarded_for"'; 
      access_log    /var/log/nginx/POD_NAME/access.log;
      server_tokens off;
      sendfile            on; 
      tcp_nopush          on; 
      tcp_nodelay         on; 
      keepalive_timeout   65; 
      types_hash_max_size 2048;
      include             /etc/nginx/mime.types; 
      default_type        application/octet-stream;
      server {
        listen 8080 default_server;
        server_name _;
        location / {
          root /usr/share/nginx/html;
          index index.html index.htm;
        }
        location /healthz {
          access_log off;
          return 200;
        }
      } 
    }

