apiVersion: v1
kind: Namespace
metadata:
  labels:
    argocd.argoproj.io/managed-by: gitops
  name: stage-prod
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stage-prod
  namespace: gitops
spec:
  destination:
    namespace: stage-prod
    server: https://kubernetes.default.svc
  project: default
  source:
    path: webserver/overlays/prod
    repoURL: git@github.com:dstraub/do180-sample.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gitops
  namespace: stage-prod
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- kind: ServiceAccount
  name: gitops-argocd-application-controller
  namespace: gitops

