apiVersion: v1
kind: Namespace
metadata:
  labels:
    argocd.argoproj.io/managed-by: openshift-operators
  name: stage-prod
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stage-prod
  namespace: openshift-operators
spec:
  destination:
    namespace: stage-prod
    server: https://kubernetes.default.svc
  project: default
  source:
    path: webserver/overlays/prod
    repoURL: git@github.com:dstraub/do180-sample.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: false

