apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret
metadata:
  name: registry-conf
spec:
  refreshInterval: 1m
  namespaceSelector:
    matchLabels:
      ext-secret-registry-conf: "true"
  externalSecretSpec:
    secretStoreRef:
      kind: ClusterSecretStore
      name: external-secrets
    target:
      name: registry-conf
      creationPolicy: Owner
      template:
        type: kubernetes.io/dockerconfigjson
    dataFrom:
    - extract:
        key: registry-conf

