apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: external-secrets
spec:
  provider:
    kubernetes:
      remoteNamespace: external-secrets
      server:
        url: kubernetes.default
        caProvider:
          type: ConfigMap
          key: ca.crt
          name: kube-root-ca.crt
          namespace: external-secrets
      auth:
        serviceAccount:
          name: secrets-reader
          namespace: external-secrets


