apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret
metadata:
  name: ssh-dir
spec:
  refreshInterval: 1m
  namespaceSelector:
    matchLabels:
      ext-secret-ssh-dir: "true"
  externalSecretSpec:
    secretStoreRef:
      kind: ClusterSecretStore
      name: external-secrets
    target:
      name: ssh-dir
      creationPolicy: Owner
    dataFrom:
    - extract:
        key: ssh-dir

