kind: Service
apiVersion: v1
metadata:
  name: {{ include "webserver.fullname" . }}
  labels:
    {{- include "webserver.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "webserver.selectorLabels" . | nindent 4 }}
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP

