apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: webserver
  labels:
    app: webserver
spec:
  host: test.cluster.straubcloud.de
  to:
    kind: Service
    name: webserver
  port:
    targetPort: http
