apiVersion: v1
kind: Service
metadata:
  labels:
    app: mysql
  name: mysql-np
spec:
  selector:
    app: mysql
  type: NodePort
  ports:
  - name: mysql
    port: 3306
    protocol: TCP
    targetPort: 3306

