apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stage-test
  namespace: gitops
spec:
  destination:
    namespace: stage-test
    server: https://kubernetes.default.svc
  project: default
  source:
    path: webserver/helm/chart
    repoURL: git@github.com:dstraub/do180-sample.git
    targetRevision: HEAD
    helm:
      releaseName: webserver
      valueFiles:
      - stage-test/values.yml 
  syncPolicy:
    automated:
      prune: true
      selfHeal: false

