apiVersion: v1
kind: Namespace
metadata:
  name: webserver-build
  labels:
    ext-secret-registry-conf: "true"
    ext-secret-ssh-dir: "true"
    ext-secret-gitops-admin: "true"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
imagePullSecrets:
- name: registry-conf
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pipeline
imagePullSecrets:
- name: registry-conf

